📚 Update section for email in development setup
pretalx/pretalx pull request #1117
Opened 2021-06-04 09:28 UTC by cfra

When running in development mode, the server is using Django's console
email backend and prints mails to stdout instead of sending them via
SMTP.

The mail configuration is also not loaded by `settings.py` leading to the
proposed port setting of 1025 to be ignored, and default settings
showing up in the admin information, which was a bit confusing to me.

Python's debugging SMTP server was still news to me, so I think it is
useful to keep that information around, in case somebody needs to test
interactions via SMTP.

This PR closes/references issue #XX. It does so by …

## How Has This Been Tested?

## Screenshots (if appropriate):

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My change is listed in the CHANGELOG.rst if appropriate.

2021-06-04 09:40 UTC, rixx requested changes
Thank you! Could you change this to also keep the config snippet in there? I like to make stuff like that easy to copy and paste, which "by specifying ``localhost``" isn't really.

2021-06-06 14:58 UTC, cfra commented
I removed it intentionally, because it does not work, because these settings are ignored when debugging is enabled:

```python
# from settings.py

## EMAIL SETTINGS
MAIL_FROM = SERVER_EMAIL = DEFAULT_FROM_EMAIL = config.get("mail", "from")
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_HOST = config.get("mail", "host")
    EMAIL_PORT = config.get("mail", "port")
    EMAIL_HOST_USER = config.get("mail", "user")
    EMAIL_HOST_PASSWORD = config.get("mail", "password")
    EMAIL_USE_TLS = config.getboolean("mail", "tls")
    EMAIL_USE_SSL = config.getboolean("mail", "ssl")
```

The last section about "specifying localhost" relates to event settings that are configured using the form in the back end as far as I understood it, and not via the settings file.

As far as I can tell, the config snippet I remove will only work if `DEBUG = False` is configured, which I assumed is not commonly done in a development setup.

I think it would be good to point out that the included snippet will not work with `DEBUG = True`, if it is included in the dev setup documentation, because it was somewhat confusing to me.

What do you think?

2021-06-06 15:35 UTC, rixx commented
Apologies, I misunderstood parts of this PR. I jumped to thinking about making the behaviour described in the documentation work, rather than changing the documentation. Still, working documentation is better than incorrect documentation, so I'll merge this with thanks!

2021-06-06 15:35 UTC, rixx approved these changes

2021-06-06 15:35 UTC, merged